Repository codesquad-member-2020/baseball-03, pull requests merged in 2020-05, with the labels that each got.

#6 [#5] UI구성 - 로그인 화면
  iOS/.gitignore
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/BaseBall/BaseBall.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/BaseBall/BaseBall/AppDelegate.swift
  iOS/BaseBall/BaseBall/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/Doosan.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/Hanwha.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/KT.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/Kia.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/Kiwoom.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/LG.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/Lotte.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/NC.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/SK.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Color/Samsung.colorset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Doosan.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Doosan.imageset/Doosan.png
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Hanwha.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Hanwha.imageset/Hanwha.png
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/KT.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/KT.imageset/KT.png
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Kia.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Kia.imageset/Kia.png
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Kiwoom.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Kiwoom.imageset/Kiwoom.png
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/LG.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/LG.imageset/LG.png
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Lotte.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Lotte.imageset/Lotte.png
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/NC.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/NC.imageset/NC.png
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/SK.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/SK.imageset/SK.png
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Samsung.imageset/Contents.json
  iOS/BaseBall/BaseBall/Assets.xcassets/Logo/Samsung.imageset/Samsung.png
  iOS/BaseBall/BaseBall/Base.lproj/LaunchScreen.storyboard
  iOS/BaseBall/BaseBall/Base.lproj/Main.storyboard
  iOS/BaseBall/BaseBall/FirstViewController.swift
  iOS/BaseBall/BaseBall/GameListViewController.swift
  iOS/BaseBall/BaseBall/Info.plist
  iOS/BaseBall/BaseBall/LoginViewController.swift
  iOS/BaseBall/BaseBallTests/BaseBallTests.swift
  iOS/BaseBall/BaseBallTests/Info.plist
Labels: feature, iOS

#13 [iOS] UI 구성 - GameListView
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall/Base.lproj/Main.storyboard
  iOS/BaseBall/BaseBall/GameListView/GameListViewController.swift
  iOS/BaseBall/BaseBall/GameListView/View/GameListLabel.swift
  iOS/BaseBall/BaseBall/GameListView/View/GameListStackView.swift
  iOS/BaseBall/BaseBall/GameListView/View/GameListView.swift
  iOS/BaseBall/BaseBall/GameView/GameViewController.swift
  iOS/BaseBall/BaseBall/LoginView/LoginViewController.swift
  iOS/BaseBall/BaseBall/LoginViewController.swift
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/Doosan.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/Hanwha.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/KT.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/Kia.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/Kiwoom.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/LG.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/Lotte.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/NC.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/SK.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/Samsung.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Doosan.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Doosan.imageset/Doosan.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Hanwha.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Hanwha.imageset/Hanwha.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/KT.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/KT.imageset/KT.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Kia.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Kia.imageset/Kia.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Kiwoom.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Kiwoom.imageset/Kiwoom.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/LG.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/LG.imageset/LG.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Lotte.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Lotte.imageset/Lotte.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/NC.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/NC.imageset/NC.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/SK.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/SK.imageset/SK.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Samsung.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo/Samsung.imageset/Samsung.png
  iOS/BaseBall/BaseBall/StroyBoard/Base.lproj/LaunchScreen.storyboard
  iOS/BaseBall/BaseBall/StroyBoard/Base.lproj/Main.storyboard
Labels: feature, iOS

#15 [#14] 스프링 부트 프로젝트 생성
  be/.gitignore
  be/.idea/$CACHE_FILE$
  be/.idea/.name
  be/.idea/jarRepositories.xml
  be/.idea/misc.xml
  be/.idea/vcs.xml
  be/README.md
  be/be.iml
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/codesquad/team3/baseball/BaseballApplication.java
  be/src/main/resources/application.properties
  be/src/test/java/com/codesquad/team3/baseball/BaseballApplicationTests.java
Labels: BE, feature

#16 [iOS] UI구성 - attack UI
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall/GameListView/GameListViewController.swift
  iOS/BaseBall/BaseBall/GameView/GameViewController.swift
  iOS/BaseBall/BaseBall/GameView/TableViewDataSource/CurrentPlayerDataSource.swift
  iOS/BaseBall/BaseBall/GameView/TableViewDataSource/CurrentRecordDataSource.swift
  iOS/BaseBall/BaseBall/GameView/View/CurrentPlayerCell.swift
  iOS/BaseBall/BaseBall/GameView/View/CurrentRecordCell.swift
  iOS/BaseBall/BaseBall/GameView/View/ElectronicView.swift
  iOS/BaseBall/BaseBall/GameView/View/FieldView.swift
  iOS/BaseBall/BaseBall/GameView/View/ScoreView.swift
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/FieldColor.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/GroundColor.colorset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Doosan_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Doosan_thumbnail.imageset/Doosan_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Hanwha_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Hanwha_thumbnail.imageset/Hanwha_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/KT_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/KT_thumbnail.imageset/KT_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Kia_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Kia_thumbnail.imageset/Kia_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Kiwoom_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Kiwoom_thumbnail.imageset/Kiwoom_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/LG_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/LG_thumbnail.imageset/LG_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Lotte_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Lotte_thumbnail.imageset/Lotte_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/NC_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/NC_thumbnail.imageset/NC_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/SK_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/SK_thumbnail.imageset/SK_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Samsung_thumbnail.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Logo_thumbnail/Samsung_thumbnail.imageset/Samsung_thumbnail.png
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/ball.imageset/Contents.json
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/ball.imageset/ball.png
  iOS/BaseBall/BaseBall/StroyBoard/Base.lproj/Main.storyboard
Labels: feature, iOS

#19 [#18] 환경별 설정파일 구분, DB 연결 테스트
  be/build.gradle
  be/src/main/resources/application-local.properties
  be/src/main/resources/application-master.properties
  be/src/main/resources/application.properties
  be/src/test/java/com/codesquad/team3/baseball/DBConnectTest/DBConnectionTest.java
Labels: BE, feature

#22 [#7] DB 스키마 파일 및 구문 작성
  be/src/main/resources/application.properties
  be/src/main/resources/schema.sql
Labels: BE, feature

#27 [iOS] setup network connection
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall/Controller/TeamListUseCase.swift
  iOS/BaseBall/BaseBall/LoginView/LoginViewController.swift
  iOS/BaseBall/BaseBall/Model/Extension/UIColorExtension.swift
  iOS/BaseBall/BaseBall/Model/Manager/TeamListManager.swift
  iOS/BaseBall/BaseBall/Model/Network/EndPoint.swift
  iOS/BaseBall/BaseBall/Model/Network/NetworkManager.swift
  iOS/BaseBall/BaseBall/Model/Network/Request.swift
  iOS/BaseBall/BaseBall/Model/TeamList.swift
  iOS/BaseBall/BaseBall/Resources/Assets.xcassets/Color/Hanwha.colorset/Contents.json
Labels: feature, iOS

#35 [iOS] network연결 - game list view
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall/Controller/ImageUseCase.swift
  iOS/BaseBall/BaseBall/Controller/MatchListUseCase.swift
  iOS/BaseBall/BaseBall/Controller/TeamListUseCase.swift
  iOS/BaseBall/BaseBall/GameListView/GameListViewController.swift
  iOS/BaseBall/BaseBall/GameListView/View/GameListView.swift
  iOS/BaseBall/BaseBall/LoginView/LoginViewController.swift
  iOS/BaseBall/BaseBall/Model/Manager/MatchListManager.swift
  iOS/BaseBall/BaseBall/Model/MatchList.swift
  iOS/BaseBall/BaseBall/Model/Network/EndPoint.swift
  iOS/BaseBall/BaseBall/StroyBoard/Base.lproj/Main.storyboard
Labels: feature, iOS

#34 [#31][#32] 팀 리스트 반환, 경기 리스트 반환 api 구현
  be/src/main/java/com/codesquad/team3/baseball/controller/MatchingController.java
  be/src/main/java/com/codesquad/team3/baseball/dao/MainDAO.java
  be/src/main/java/com/codesquad/team3/baseball/dao/MatchingDAO.java
  be/src/main/java/com/codesquad/team3/baseball/service/MatchingService.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
Labels: BE, feature

#38 [#37] 게임 초기화 데이터 추가 및 반환
  be/src/main/java/com/codesquad/team3/baseball/controller/GameController.java
  be/src/main/java/com/codesquad/team3/baseball/dao/GameDAO.java
  be/src/main/java/com/codesquad/team3/baseball/domain/HalfInning.java
  be/src/main/java/com/codesquad/team3/baseball/dto/PlayerDTO.java
  be/src/main/java/com/codesquad/team3/baseball/service/GameService.java
  be/src/main/resources/schema.sql
Labels: BE, feature

#39 Feature i os/reflect feedback
  iOS/BaseBall/BaseBall.xcodeproj/project.pbxproj
  iOS/BaseBall/BaseBall/Controller/ImageUseCase.swift
  iOS/BaseBall/BaseBall/Controller/MatchListUseCase.swift
  iOS/BaseBall/BaseBall/Controller/TeamListUseCase.swift
  iOS/BaseBall/BaseBall/GameListView/GameListViewController.swift
  iOS/BaseBall/BaseBall/GameListView/View/GameListView.swift
  iOS/BaseBall/BaseBall/GameView/GameViewController.swift
  iOS/BaseBall/BaseBall/GameView/TableViewDataSource/PlayerDataSource.swift
  iOS/BaseBall/BaseBall/GameView/TableViewDataSource/RecordDataSource.swift
  iOS/BaseBall/BaseBall/GameView/View/PlayerCell.swift
  iOS/BaseBall/BaseBall/GameView/View/RecordCell.swift
  iOS/BaseBall/BaseBall/LoginView/LoginViewController.swift
  iOS/BaseBall/BaseBall/Model/Extension/UIColorExtension.swift
  iOS/BaseBall/BaseBall/Model/Network/NetworkManager.swift
  iOS/BaseBall/BaseBall/Model/Network/Request.swift
  iOS/BaseBall/BaseBall/StroyBoard/Base.lproj/Main.storyboard
Labels: iOS, refactor

#45 [#42] 수비 api 구현
  be/src/main/java/com/codesquad/team3/baseball/controller/GameController.java
  be/src/main/java/com/codesquad/team3/baseball/dao/GameDAO.java
  be/src/main/java/com/codesquad/team3/baseball/dao/InGameDAO.java
  be/src/main/java/com/codesquad/team3/baseball/domain/AtBat.java
  be/src/main/java/com/codesquad/team3/baseball/domain/Game.java
  be/src/main/java/com/codesquad/team3/baseball/domain/GameLog.java
  be/src/main/java/com/codesquad/team3/baseball/domain/HalfInning.java
  be/src/main/java/com/codesquad/team3/baseball/domain/Player.java
  be/src/main/java/com/codesquad/team3/baseball/domain/Team.java
  be/src/main/java/com/codesquad/team3/baseball/domain/TeamGame.java
  be/src/main/java/com/codesquad/team3/baseball/dto/PitchingDTO.java
  be/src/main/java/com/codesquad/team3/baseball/exception/InAppropriateRequest.java
  be/src/main/java/com/codesquad/team3/baseball/service/GameService.java
  be/src/main/java/com/codesquad/team3/baseball/service/InGameService.java
  be/src/main/resources/schema.sql
Labels: BE, feature

#51 [#50] 선수 명단, 점수판 목업 api 구현
  be/src/main/java/com/codesquad/team3/baseball/controller/MockController.java
Labels: BE

#57 [#55] Cors 방지 설정 추가
  be/src/main/java/com/codesquad/team3/baseball/config/CorsConfig.java
Labels: BE, bug
